FROM golang:1.23-alpine

WORKDIR /app

# Enable CGO for go-sqlite3
ENV CGO_ENABLED=1
ENV GOOS=linux

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o server ./cmd/main.go

EXPOSE 8080

CMD ["./server"]